name: weather_app
description: Flutter test application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_bloc: ^7.0.0
  equatable: ^2.0.2

  # Icons
  cupertino_icons: ^1.0.2

  # Remote connections
  http: ^0.13.3
  http_parser: ^4.0.0

  # Local storage
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  analyzer: ^1.7.1

  # Geolocation
  geolocator: ^7.0.3

  # Check internet connectivity
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Local storage/code generation
  hive_generator: ^1.1.0
  build_runner: ^2.0.4

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
